### ISSUE TITLE
Request for to_s

### ISSUE THREAD

**Issue by cfourt** [bretts/to_histogram#1]
This is super helpful, I'm using this in a script which writes analysis to a file. I'm collecting strings to ultimately write to a file, and I'd like to save the output that would normally go to `stdout` in a variable for use later

Not an issue, but a feature request (or clarification if I missed something). 

Thanks!

**Comment by bretts** [comment]
Hey, glad you find it useful! Here is what I think you're describing:

```
require 'to_histogram'
# Create the histogram
histogram = [2,4,0,5,2,4,1,0,1,3,7,5,3,3,0,0,2,3,0,8,6,5,0,10,11,12].to_histogram(print_info: false)

# Do some things
# .
# .
# .

# Print the histogram out later to a file
file = File.open('output.txt', 'a')
ToHistogram::StdoutPrint.new(histogram, file).invoke
```

Let me know if you need something different and I can make a change.
 Brett

**Comment by cfourt** [comment]
That that works! Thank you Brett :)
